#trains model on data formatted and generated by data collector file

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
import pickle

# Load the CSV
data = pd.read_csv('lol_training_data.csv')

X = data.drop(['match_id', 'timestamp_min', 'blue_win'], axis=1)
Y = data['blue_win']




X_train, X_test, y_train, y_test = train_test_split(
    X, Y, 
    test_size=0.2,    
    random_state=42   
)


scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)



print(scaler.score(X,y))